/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Model_test.gltf 
*/
'use client';
import React from 'react'
import { useGLTF, PerspectiveCamera, useTexture } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"
import { useEffect, useRef, useState } from "react"
import * as THREE from "three"
import { Vector3 } from "three"
import { useConfigurator } from "./Configurator"

const ANIM_SPEED = 1;
const Model_test =(props) => {
  const { nodes, materials } = useGLTF('/models/Model_test.gltf')
  //const {texture} = useTexture()
  const StainlessTextureProps = useTexture({
    map: "./Material/Brushed Stainless/Poliigon_MetalSteelBrushed_7174_BaseColor.jpg",
    normalMap: "./Material/Brushed Stainless/Poliigon_MetalSteelBrushed_7174_Normal.png",
    roughnessMap: "./Material/Brushed Stainless/Poliigon_MetalSteelBrushed_7174_Roughness.jpg",
    aoMap: "./Material/Brushed Stainless/Poliigon_MetalSteelBrushed_7174_AmbientOcclusion.jpg",
  });

    const GalvanizedTextureProps = useTexture({
    map: "./Material/Galvanized/MetalGalvanizedSteelWorn001_COL_4K_METALNESS.jpg",
    normalMap: "./Material/Galvanized/MetalGalvanizedSteelWorn001_NRM_4K_METALNESS.jpg",
    roughnessMap: "./Material/Galvanized/MetalGalvanizedSteelWorn001_ROUGHNESS_4K_METALNESS.jpg",
    aoMap: "./Material/Brushed Stainless/Poliigon_MetalSteelBrushed_7174_AmbientOcclusion.jpg",
    metalnessMap: "./Material/Galvanized/MetalGalvanizedSteelWorn001_NRM_4K_METALNESS.jpg"
  });

  GalvanizedTextureProps.map.repeat.set(3, 3);
  GalvanizedTextureProps.normalMap.repeat.set(3, 3);
  GalvanizedTextureProps.roughnessMap.repeat.set(3, 3);
  GalvanizedTextureProps.aoMap.repeat.set(3, 3);
  GalvanizedTextureProps.map.wrapS = GalvanizedTextureProps.map.wrapT = THREE.MirroredRepeatWrapping;
  GalvanizedTextureProps.normalMap.wrapS = GalvanizedTextureProps.normalMap.wrapT = THREE.MirroredRepeatWrapping;
  GalvanizedTextureProps.roughnessMap.wrapS = GalvanizedTextureProps.roughnessMap.wrapT = THREE.MirroredRepeatWrapping;
  GalvanizedTextureProps.aoMap.wrapS = GalvanizedTextureProps.aoMap.wrapT = THREE.RepeatWrapping;
  StainlessTextureProps.map.repeat.set(3, 3);
  StainlessTextureProps.normalMap.repeat.set(3, 3);
  StainlessTextureProps.roughnessMap.repeat.set(3, 3);
  StainlessTextureProps.aoMap.repeat.set(3, 3);
  StainlessTextureProps.map.wrapS = StainlessTextureProps.map.wrapT = THREE.MirroredRepeatWrapping;
  StainlessTextureProps.normalMap.wrapS = StainlessTextureProps.normalMap.wrapT = THREE.MirroredRepeatWrapping;
  StainlessTextureProps.roughnessMap.wrapS = StainlessTextureProps.roughnessMap.wrapT = THREE.MirroredRepeatWrapping;
  StainlessTextureProps.aoMap.wrapS = StainlessTextureProps.aoMap.wrapT = THREE.RepeatWrapping;
 

  const { tableWidth } = useConfigurator();
  const { tableLength } = useConfigurator();
  const { tableHeight } = useConfigurator();
  const { Material} = useConfigurator();
  const { tablecolor} = useConfigurator();
  const material = new THREE.MeshStandardMaterial(StainlessTextureProps);
  material.metalness = 1

  //const top = useRef();
   const Bottom = useRef();

  useFrame((_state, delta) => {
    const tableWidthScale = tableWidth / 100;
    const targetScale = new Vector3(1, 1, tableWidthScale);

    //top.current.scale.lerp(targetScale, delta * ANIM_SPEED);
     Bottom.current.scale.lerp(targetScale, delta * ANIM_SPEED);
    const tableLengthScale = tableLength / 100;
    const targetScale1 = new Vector3(tableLengthScale, 1, 1);
     const tableHeighthScale = tableHeight/ 100;
    const targetScale2 = new Vector3(1, tableHeighthScale, 1);


    //top.current.scale.lerp(targetScale1, delta * ANIM_SPEED);
      Bottom.current.scale.lerp(targetScale1, delta * ANIM_SPEED);

         // top.current.scale.lerp(targetScale2, delta * ANIM_SPEED);
      Bottom.current.scale.lerp(targetScale2, delta * ANIM_SPEED);

/*
    const targetLeftPosition = new Vector3(-1.5 * tableWidthScale, 0, 0);
    leftLegs.current.position.lerp(targetLeftPosition, delta * ANIM_SPEED);
*/
    const targetRightPosition = new Vector3(44.943 * tableLengthScale, -1.332, 0.105);

  });
  return (
    <group {...props} dispose={null} onDoubleClick={e => {e.stopPropagation(); clickHandler(e)}}>
      <group scale={0.025 }>
        <group position={[-45, 0, -18]}ref={Bottom}>  
          <group position={[47.306, 6, 34.5]} >
            <group position={[-47.306, -6, -34.5]} >
              <mesh geometry={nodes['315_counter_channel_3_1'].geometry} position={[45, 7.688, 2.41]} rotation={[-Math.PI / 2, 0, -Math.PI]} castshadow/>
              <group position={[9.901, 8.563, 33.735]}>
                <mesh geometry={nodes['315_top_tube_6_1'].geometry} position={[-0.873, -0.875, -17.735]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1}
                />
                </mesh>
                <mesh geometry={nodes['315_comp_slide_1_1'].geometry} position={[7.75, -0.875, -9.66]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1}
                />
                </mesh>
                <mesh geometry={nodes['315_comp_slide_2_1'].geometry} position={[-7.75, -0.875, -9.66]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1}
                />
                </mesh>
                <mesh geometry={nodes['315_comp_slide_3_1'].geometry} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} 
                />
                </mesh>
              </group>
              <mesh geometry={nodes['315_counter_channel_1_1'].geometry} position={[9.028, 7.688, 33.59]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes['315_stringer_1_1'].geometry} position={[0.25, 7.688, 18]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes['315_stringer_2_1'].geometry}  position={[17.806, 7.688, 18]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes['315_counter_channel_2_1'].geometry}  position={[83.278, 7.688, 33.59]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes['315_stringer_3_1'].geometry}  position={[76.806, 7.688, 18]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes['315_stringer_4_1'].geometry}  position={[89.75, 7.688, 18]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            </group>
            <mesh geometry={nodes['315_apron_3_1'].geometry} position={[0, 21.288, 0]}  castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <group position={[-3.819, 30, 1.395]}>
              <mesh geometry={nodes['315_rail_1_1'].geometry}  position={[14.456, 3.016, -7.856]} rotation={[-1.385, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes['315_top_1_2'].geometry} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1}
                color={tablecolor}
              />
              </mesh>
              <mesh geometry={nodes.cold_pan_corner_fill_4.geometry}  position={[-13.136, 2.705, -10.267]} rotation={[-2.956, Math.PI / 4, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes.cold_pan_corner_fill_5.geometry}  position={[-13.136, 5.053, -22.784]} rotation={[0.185, Math.PI / 4, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes.cold_pan_corner_fill_6.geometry} position={[41.974, 5.053, -22.784]} rotation={[0.185, -Math.PI / 4, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes.cold_pan_corner_fill_7.geometry} position={[41.974, 2.705, -10.267]} rotation={[-2.956, -Math.PI / 4, Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes['315_ear_1_1'].geometry} position={[44.943, -1.332, -35.895]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} color={tablecolor}/></mesh>
              <mesh geometry={nodes['315_ear_2_1'].geometry}   position={[44.943, -1.332, 0.105]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} 
                color={tablecolor}
                /></mesh>
            </group>
            <mesh geometry={nodes['1023_8_315_91_1'].geometry}  position={[0, 0.145, -2.275]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_4_315_92_1'].geometry}  position={[0, 0.08, -2.18]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_5_315_93_1'].geometry}  position={[-29.403, 0.125, -16.205]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_7_315_94_1'].geometry}  position={[29.403, 22.94, -16.205]} rotation={[Math.PI, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_6_315_95_1'].geometry}  position={[0, 0.125, -30.19]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_insul_top_1_315_96_1'].geometry} position={[0, 23.065, -2.25]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_base_channel_1_315_97_1'].geometry}  position={[0, 0, -26.525]} rotation={[Math.PI / 2, 0, Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_base_channel_2_315_98_1'].geometry}  position={[0, 0, -5.875]} rotation={[Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_10_315_99_1'].geometry}  position={[0, 2.25, -4.063]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_11_315_100_1'].geometry}  position={[-27.313, 2.56, -15.988]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_12_315_101_1'].geometry}  position={[0, 2.56, -28.1]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_13_315_102_1'].geometry}  position={[27.313, 2.56, -15.988]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_16_315_103_1'].geometry}  position={[14.938, 20.08, -3.875]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_14_315_104_1'].geometry} position={[0, 2.56, -3.875]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_15_315_105_1'].geometry}  position={[-14.938, 20.08, -3.875]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_17_315_106_1'].geometry}  position={[0, 20.94, -3.935]} rotation={[Math.PI / 2, 0, Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_36_315_107_1'].geometry}   position={[0, 0.08, -2.125]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_37_315_108_1'].geometry} position={[-14.938, 1.72, -2.065]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1023_38_315_109_1'].geometry} position={[14.938, 1.72, -2.065]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_front_channel_1_5'].geometry}   position={[23.794, 14.256, -32.947]} rotation={[-Math.PI, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_front_channel_1_6'].geometry}   position={[-10.131, 14.256, -32.947]} rotation={[-Math.PI, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_front_channel_1_7'].geometry}   position={[-27.094, 14.256, -32.947]} rotation={[-Math.PI, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_front_channel_1_8'].geometry}   position={[-44.056, 14.256, -32.947]} rotation={[-Math.PI, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_front_channel_1_9'].geometry}   position={[6.831, 14.256, -32.947]} rotation={[-Math.PI, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_apron_1_1'].geometry}   position={[-37.406, 26.08, 0]}castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_lh_end_1_1'].geometry}   position={[-47.181, 0.08, -15.153]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_bu_1_1'].geometry}  position={[-47.126, 15.016, -0.75]} rotation={[-Math.PI, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_lh_end_2_1'].geometry}   position={[-29.5, 0.08, -15.153]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_rh_hand_1_1'].geometry}   position={[29.5, 0.08, -15.153]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_mullion_1_1'].geometry}   position={[0, 0.08, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_apron_2_1'].geometry}  position={[32.694, 26.08, -33]} rotation={[-Math.PI, 0, Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_mullion_2_1'].geometry}  position={[41.631, 0.08, -33]} rotation={[-Math.PI, 0, Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_bu_2_1'].geometry}  position={[41.626, 15.016, -32.25]} rotation={[0, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_bu_3_1'].geometry}  position={[42.504, 15.016, -32.25]} rotation={[0, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_mullion_3_1'].geometry}   position={[36.037, 0.08, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_bu_4_1'].geometry}  position={[41.671, 15.016, -0.75]} rotation={[-Math.PI, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_bu_5_1'].geometry}  position={[29.57, 15.016, -0.75]} rotation={[-Math.PI, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_bu_6_1'].geometry}  position={[24.629, 14.266, -32.25]} rotation={[0, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes.access_panel_315_84_1.geometry}   position={[-37.406, 0.188, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes.access_panel_315_192_1.geometry}  position={[32.694, 0.188, -33]} rotation={[-Math.PI, 0, Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_panel_1_1_1'].geometry} position={[-11.244, 0.08, -33]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_top_channel_1_1'].geometry} position={[-3.204, 28.326, -32.815]} rotation={[Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_top_tube_1_1'].geometry}  position={[5.628, 29.826, -4.625]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_top_tube_2_1'].geometry}  position={[-38.309, 29.826, -9.25]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_top_tube_3_1'].geometry}position={[-38.309, 29.826, -19.25]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_top_tube_4_1'].geometry}  position={[40.694, 29.826, -16.5]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['315_top_tube_5_1'].geometry} position={[-21.275, 29.826, -18.215]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
          </group>
      
          <group position={[57.906, 40.616, 19.508]} rotation={[0.185, 0, 0]}>
            <mesh geometry={nodes['1039_5_315_219_2'].geometry}   position={[-28.344, 0.094, 0.375]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_5_315_219_3'].geometry}   position={[28.404, 0.094, 0.375]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_1_315_215_1'].geometry}   position={[0, 0.75, 7.736]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_2_315_216_1'].geometry}   position={[0, 0.75, 0.248]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_3_315_217_2'].geometry}   position={[28.604, 0, -6.256]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_4_315_218_2'].geometry}  position={[28.295, 0.144, -5.311]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_6_315_220_2'].geometry}  position={[28.344, 0.406, -0.065]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_7_315_221_2'].geometry}  position={[28.221, 0.406, -0.065]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1174_4'].geometry}  position={[28.19, 0.394, -6.843]} rotation={[Math.PI, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1174_5'].geometry} position={[28.19, 0.394, -4.843]} rotation={[Math.PI, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_3_315_217_3'].geometry}   position={[-28.424, 0, -6.256]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_4_315_218_3'].geometry}  position={[-28.22, 0.144, -5.311]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1039_7_315_221_3'].geometry} position={[-28.221, 0.406, -0.065]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1174_6'].geometry} position={[-28.19, 0.394, -4.843]} rotation={[Math.PI, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1174_7'].geometry}  position={[-28.19, 0.394, -6.843]} rotation={[Math.PI, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
          </group>
          <group position={[57.906, 40.616, 19.508]} rotation={[0.185, 0, 0]}>
            <mesh geometry={nodes['1041_11_315_198_1'].geometry}   position={[0, -9, 5.425]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1041_10_315_199_2'].geometry}   position={[-27.125, -8.408, 0]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['1041_10_315_199_3'].geometry}   position={[27.125, -8.408, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['4464k38_1'].geometry}  position={[25.875, -10.15, 4.688]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_18'].geometry}   position={[-25.692, -1.563, 7.505]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_19'].geometry}   position={[-17.128, -1.563, 7.505]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_20'].geometry}   position={[-8.564, -1.563, 7.505]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_21'].geometry}   position={[0, -1.563, 7.505]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_22'].geometry}   position={[8.564, -1.563, 7.505]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_23'].geometry}   position={[17.128, -1.563, 7.505]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_24'].geometry}   position={[25.692, -1.563, 7.505]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_25'].geometry}   position={[28.692, -1.563, 4.505]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_26'].geometry}   position={[28.692, -1.563, -4.505]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_27'].geometry}   position={[25.692, -1.563, -7.505]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_28'].geometry}   position={[17.128, -1.563, -7.505]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_29'].geometry}   position={[8.564, -1.563, -7.505]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_30'].geometry}   position={[0, -1.563, -7.505]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_31'].geometry}   position={[-8.564, -1.563, -7.505]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_32'].geometry}   position={[-17.128, -1.563, -7.505]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_33'].geometry}   position={[-25.692, -1.563, -7.505]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_34'].geometry}   position={[-28.692, -1.563, -4.505]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3634_35'].geometry}   position={[-28.692, -1.563, 4.505]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_16'].geometry}   position={[-24.737, -4.561, 6.55]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_17'].geometry}   position={[-14.842, -4.561, 6.55]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_18'].geometry}   position={[-4.948, -4.561, 6.55]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_19'].geometry}  position={[4.948, -4.561, 6.55]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_20'].geometry}  position={[14.842, -4.561, 6.55]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_21'].geometry}  position={[24.737, -4.561, 6.55]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_22'].geometry}  position={[27.737, -4.561, 3.55]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_23'].geometry} position={[27.737, -4.561, -3.55]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_24'].geometry} position={[24.737, -4.561, -6.55]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_25'].geometry} position={[14.842, -4.561, -6.55]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_26'].geometry}  position={[4.948, -4.561, -6.55]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
            <mesh geometry={nodes['3635_27'].geometry}  position={[-4.948, -4.561, -6.55]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['3635_28'].geometry}  position={[-14.842, -4.561, -6.55]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            <mesh geometry={nodes['3635_29'].geometry}  position={[-24.737, -4.561, -6.55]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['3635_30'].geometry}  position={[-27.737, -4.561, -3.55]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['3635_31'].geometry}  position={[-27.737, -4.561, 3.55]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
          </group>
          <group position={[32.369, 16.27, 32.375]}>
            <mesh geometry={nodes['1009_2_315_130_1'].geometry} position={[0, 0.08, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1009_3_315_131_1'].geometry}  position={[0, 0.06, -1.75]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['1009_8_315_133_1'].geometry}  position={[-9.85, 1, -1.825]} rotation={[-Math.PI, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1009_9_315_134_1'].geometry}  position={[9.85, 1, -1.825]} rotation={[-Math.PI, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>    
          </group>
          <group position={[62.244, 16.27, 32.375]}>
            <mesh geometry={nodes['1009_2_315_162_1'].geometry}  position={[0, 0.08, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            <mesh geometry={nodes['1009_3_315_163_1'].geometry}  position={[0, 0.06, -1.75]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1009_8_315_165_1'].geometry}  position={[-9.85, 1, -1.825]} rotation={[-Math.PI, 0, Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1009_9_315_166_1'].geometry}    position={[9.85, 1, -1.825]} rotation={[-Math.PI, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
          </group>
          <group position={[62.806, 7.563, 3.25]} rotation={[0, Math.PI / 2, 0]}>
            <group position={[-29.5, 0, -60.931]}>
              <mesh geometry={nodes['315_leg_1_1'].geometry}   rotation={[Math.PI / 2, -Math.PI / 2, 0]}  castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
              <mesh geometry={nodes.bullet_foot_8.geometry}   position={[0, -5.75, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            </group>
            <group position={[-29.5, 0, 26.069]}>
              <mesh geometry={nodes['315_leg_2_1'].geometry}   rotation={[Math.PI / 2, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
              <mesh geometry={nodes.bullet_foot_9.geometry}   position={[0, -5.75, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            </group>
            <group position={[-27.75, -1.563, -43.25]}>
              <mesh geometry={nodes['315_leg_3_1'].geometry}   rotation={[Math.PI / 2, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
              <mesh geometry={nodes.bullet_foot_10.geometry}   position={[0, -4.188, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            </group>
            <group position={[-27.75, -1.563, 12.25]}>
              <mesh geometry={nodes['315_leg_4_1'].geometry}   rotation={[Math.PI / 2, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes.bullet_foot_11.geometry}   position={[0, -4.188, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            </group>
            <group position={[0, 0, -60.931]}>
              <mesh geometry={nodes['315_leg_5_1'].geometry}   rotation={[Math.PI / 2, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes.bullet_foot_12.geometry}   position={[0, -5.75, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            </group>
            <group position={[0, 0, 26.069]}>
              <mesh geometry={nodes['315_leg_6_1'].geometry}   rotation={[Math.PI / 2, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
              <mesh geometry={nodes.bullet_foot_13.geometry}  position={[0, -5.75, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            </group>
            <group position={[0, 0, -43.25]}>
              <mesh geometry={nodes['315_leg_7_1'].geometry}   rotation={[Math.PI / 2, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
              <mesh geometry={nodes.bullet_foot_14.geometry}   position={[0, -5.75, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            </group>
            <mesh geometry={nodes['315_leg_8_1'].geometry}   rotation={[Math.PI / 2, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes.bullet_foot_15.geometry}  position={[0, -5.75, 0]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>    
          </group>
          <mesh geometry={nodes.Cube.geometry}  position={[76.327, 17.6, 20.168]} scale={[0.8, 21.4, 23.5]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
          <mesh geometry={nodes['Cube_#1'].geometry}  position={[65.893, 28.625, 20.168]} rotation={[0, 0, 1.549]} scale={[0.8, 21.4, 23.5]}visible={false} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>         
   //topdrawer      
          <group position={[62.244, 17.458, 34.5]} >
            <mesh geometry={nodes['1018_1_315_181_1'].geometry}  position={[0, 0.08, 0]}    castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            <mesh geometry={nodes['1018_2_315_182_1'].geometry} position={[0, 9.375, -0.08]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            <mesh geometry={nodes['1018_3_315_183_1'].geometry}  position={[0, 0.313, -1.475]} rotation={[-Math.PI, 0, -Math.PI]}  castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            <mesh geometry={nodes['1018_4_315_184_1'].geometry}  position={[0, 0.125, -1.975]} rotation={[-Math.PI, 0, -Math.PI]}  castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
          </group>
          <group position={[62.244, 24.645, 33.025]}>
            <mesh geometry={nodes['1004_2_4'].geometry} position={[0, -3.405, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1004_3_4'].geometry}  position={[0, -3.405, -26.37]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['1004_4_4'].geometry} position={[0, 0, -13.15]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['3473_8'].geometry}  position={[-8.935, -3.34, -24.808]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            <mesh geometry={nodes['3473_9'].geometry}  position={[8.935, -3.34, -24.808]} rotation={[-Math.PI / 2, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>    
          </group>
//bottomdrawer          
          <group position={[62.244, 6.688, 34.5]}>
            <mesh geometry={nodes['1018_1_315_170_1'].geometry}  position={[0, 0.08, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1018_2_315_171_1'].geometry}  position={[0, 10.395, -0.08]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1018_3_315_172_1'].geometry}  position={[0, 1.313, -1.475]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['1018_4_315_173_1'].geometry}  position={[0, 1.125, -1.975]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
          </group>
          <group position={[62.244, 14.895, 33.025]}>
            <mesh geometry={nodes['1004_2_5'].geometry} position={[0, -3.405, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['1004_3_5'].geometry}  position={[0, -3.405, -26.37]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['1004_4_5'].geometry}  position={[0, 0, -13.15]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['3473_10'].geometry}  position={[-8.935, -3.34, -24.808]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['3473_11'].geometry}  position={[8.935, -3.34, -24.808]} rotation={[-Math.PI / 2, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>     
          </group>
 //top drawer         
          <group position={[32.369, 17.458, 34.5]}>
            <mesh geometry={nodes['1018_1_315_149_1'].geometry}  position={[0, 0.08, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['1018_2_315_150_1'].geometry}position={[0, 9.375, -0.08]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1018_3_315_151_1'].geometry}  position={[0, 0.313, -1.475]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1018_4_315_152_1'].geometry} position={[0, 0.125, -1.975]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
          </group>
          <group position={[32.369, 24.645, 33.025]}>
            <mesh geometry={nodes['1004_2_6'].geometry}  position={[0, -3.405, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1004_3_6'].geometry} position={[0, -3.405, -26.37]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            <mesh geometry={nodes['1004_4_6'].geometry} position={[0, 0, -13.15]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh> 
            <mesh geometry={nodes['3473_12'].geometry}  position={[-8.935, -3.34, -24.808]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['3473_13'].geometry}  position={[8.935, -3.34, -24.808]} rotation={[-Math.PI / 2, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>    
          </group>
// bottom drawer 
          <group position={[32.369, 6.688, 34.5]}>
            <mesh geometry={nodes['1018_1_315_138_1'].geometry}  position={[0, 0.08, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1018_2_315_139_1'].geometry}  position={[0, 10.395, -0.08]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1018_3_315_140_1'].geometry} position={[0, 1.313, -1.475]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1018_4_315_141_1'].geometry}  position={[0, 1.125, -1.975]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>    
          </group>
          <group position={[32.369, 14.895, 33.025]}>
            <mesh geometry={nodes['1004_2_7'].geometry} position={[0, -3.405, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['1004_3_7'].geometry}  position={[0, -3.405, -26.37]} rotation={[-Math.PI, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['1004_4_7'].geometry}  position={[0, 0, -13.15]} rotation={[-Math.PI / 2, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
            <mesh geometry={nodes['3473_14'].geometry}  position={[-8.935, -3.34, -24.808]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
            <mesh geometry={nodes['3473_15'].geometry}  position={[8.935, -3.34, -24.808]} rotation={[-Math.PI / 2, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
          </group>
          <mesh geometry={nodes['315_inssul_cover_1_1'].geometry} position={[57.906, 34.951, 27.226]} rotation={[0.185, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>    
          <mesh geometry={nodes['315_inssul_cover_2_1'].geometry}  position={[57.906, 38.133, 10.262]} rotation={[-2.956, 0, Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>     
          <mesh geometry={nodes['315_inssul_cover_3_1'].geometry}  position={[57.906, 29.445, 25.176]} rotation={[0.185, 0, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>    
          <mesh geometry={nodes['315_inssul_cover_4_1'].geometry}  position={[57.906, 32.258, 10.177]} rotation={[-2.956, 0, -Math.PI]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>     
          <mesh geometry={nodes['315_rack_1_1'].geometry}  position={[21.056, 12.145, 18.513]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>   
          <mesh geometry={nodes['315_rack_2_1'].geometry}  position={[43.681, 12.145, 18.513]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>  
          <mesh geometry={nodes['315_rack_3_1'].geometry}  position={[50.931, 12.145, 18.513]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>    
          <mesh geometry={nodes['315_rack_4_1'].geometry} position={[73.556, 12.145, 18.513]} rotation={[0, -Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>
          <mesh geometry={nodes['2417_1'].geometry} material={materials['Hard Rough Plastic White #1']} position={[47.306, 25.958, 33.284]} castShadow/>
          <mesh geometry={nodes['5250_1'].geometry}  position={[47.494, 9, 18.513]} rotation={[0, Math.PI / 2, 0]} castShadow>
              <meshStandardMaterial
                {...(Material === 0 ? StainlessTextureProps : GalvanizedTextureProps)}
                metalness={1} /></mesh>                                                           
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={134.235} near={43.381} fov={87.277} position={[0.893, 0.75, 2.068]} rotation={[-0.156, 0.436, 0.072]} scale={0.025} />
      <PerspectiveCamera makeDefault={false} far={134.235} near={43.381} fov={27.628} position={[1.201, 1.124, 1.83]} rotation={[-0.374, 0.581, 0.218]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('.models/Model_test.gltf')

export default Model_test;
