# json_to_tab.ps1
# Parses JSON files in working directory and generates temp.tab with DECLARE_VARIABLE statements
# Usage: powershell -ExecutionPolicy Bypass -File json_to_tab.ps1 "C:\path\to\dir"

param(
    [Parameter(Position=0, Mandatory=$true)]
    [string]$WorkDir
)

function Get-SAType {
    param($Value)

    if ($null -eq $Value) { return $null }

    $type = $Value.GetType().Name
    switch ($type) {
        "String"  { return "STRING" }
        "Int32"   { return "INTEGER" }
        "Int64"   { return "INTEGER" }
        "Double"  { return "DOUBLE" }
        "Decimal" { return "DOUBLE" }
        "Boolean" { return "BOOL" }
        default   { return $null }
    }
}

function Format-SAValue {
    param($Value, $SAType)

    switch ($SAType) {
        "STRING"  { return "`"$Value`"" }
        "INTEGER" { return [int]$Value }
        "DOUBLE"  { return [double]$Value }
        "BOOL"    { if ($Value) { return "1" } else { return "0" } }
        default   { return $Value }
    }
}

function Process-JsonObject {
    param(
        [object]$Obj,
        [System.Collections.ArrayList]$Output
    )

    if ($null -eq $Obj) { return }

    # Handle PSCustomObject (parsed JSON)
    if ($Obj -is [PSCustomObject]) {
        foreach ($prop in $Obj.PSObject.Properties) {
            $name = $prop.Name
            $value = $prop.Value

            # Clean name for SmartAssembly (replace special chars with underscore)
            $cleanName = $name -replace '[^a-zA-Z0-9_]', '_'
            $cleanName = $cleanName.ToUpper()

            if ($null -eq $value) {
                # Skip null values
                continue
            }
            elseif ($value -is [PSCustomObject]) {
                # Recurse into nested object (no prefix)
                Process-JsonObject -Obj $value -Output $Output
            }
            elseif ($value -is [System.Collections.IEnumerable] -and -not ($value -is [string])) {
                # Handle arrays - process each element
                $index = 0
                foreach ($item in $value) {
                    $arrayName = "${cleanName}_${index}"
                    if ($item -is [PSCustomObject]) {
                        Process-JsonObject -Obj $item -Output $Output
                    }
                    else {
                        $saType = Get-SAType -Value $item
                        if ($saType) {
                            $saValue = Format-SAValue -Value $item -SAType $saType
                            # For booleans, declare as INTEGER
                            $declareType = if ($saType -eq "BOOL") { "INTEGER" } else { $saType }
                            $null = $Output.Add("DECLARE_VARIABLE $declareType $arrayName $saValue")
                        }
                    }
                    $index++
                }
            }
            else {
                # Primitive value - use only the field name (no parent prefix)
                $saType = Get-SAType -Value $value
                if ($saType) {
                    $saValue = Format-SAValue -Value $value -SAType $saType
                    # For booleans, declare as INTEGER
                    $declareType = if ($saType -eq "BOOL") { "INTEGER" } else { $saType }
                    $null = $Output.Add("DECLARE_VARIABLE $declareType $cleanName $saValue")
                }
            }
        }
    }
}

# Main execution
try {
    # Find JSON files in working directory
    $jsonFiles = Get-ChildItem -Path $WorkDir -Filter "*.json" -File

    if ($jsonFiles.Count -eq 0) {
        Write-Host "No JSON files found in: $WorkDir"
        exit 1
    }

    # Look for project-header.json in parent directory (project root)
    $projectHeaderPath = Join-Path (Split-Path $WorkDir -Parent) "project-header.json"
    $projectHeaderObj = $null
    if (Test-Path $projectHeaderPath) {
        Write-Host "Found project header: $projectHeaderPath"
        $headerContent = Get-Content -Path $projectHeaderPath -Raw
        $projectHeaderObj = $headerContent | ConvertFrom-Json
    }
    else {
        Write-Host "No project-header.json found in parent directory"
    }

    foreach ($jsonFile in $jsonFiles) {
        Write-Host "Processing: $($jsonFile.Name)"

        # Read and parse JSON
        $jsonContent = Get-Content -Path $jsonFile.FullName -Raw
        $jsonObj = $jsonContent | ConvertFrom-Json

        # Collect output lines
        $outputLines = New-Object System.Collections.ArrayList

        # Add header
        $null = $outputLines.Add("! Auto-generated from: $($jsonFile.Name)")
        $null = $outputLines.Add("! Generated by json_to_tab.ps1")
        $null = $outputLines.Add("")
        $null = $outputLines.Add("BEGIN_ASM_DESCR")
        $null = $outputLines.Add("")

        # Add project header variables first (if available)
        if ($null -ne $projectHeaderObj) {
            $null = $outputLines.Add("!-----------------------------------------------------------------------")
            $null = $outputLines.Add("! Project Header Variables")
            $null = $outputLines.Add("!-----------------------------------------------------------------------")
            Process-JsonObject -Obj $projectHeaderObj -Output $outputLines
            $null = $outputLines.Add("")
        }

        $null = $outputLines.Add("!-----------------------------------------------------------------------")
        $null = $outputLines.Add("! Item Variable Declarations")
        $null = $outputLines.Add("!-----------------------------------------------------------------------")

        # Process item JSON object
        Process-JsonObject -Obj $jsonObj -Output $outputLines

        # Add footer
        $null = $outputLines.Add("")
        $null = $outputLines.Add("END_ASM_DESCR")

        # Write temp.tab
        $outputPath = Join-Path $WorkDir "temp.tab"
        $outputLines | Out-File -FilePath $outputPath -Encoding ASCII

        Write-Host "Generated: $outputPath"
    }

    Write-Host "SUCCESS"
    exit 0
}
catch {
    Write-Host "ERROR: $($_.Exception.Message)"
    exit 1
}
